// AUTO-GENERATED by autopilot compile_test_execution_plan.py. Do not hand-edit.
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

function projectUrl(raw) {
  const value = String(raw || 'index.html');
  if (/^(https?:|file:)/.test(value)) return value;
  return pathToFileURL(path.resolve(process.cwd(), value)).href;
}

async function openTarget(page, raw) {
  await page.goto(projectUrl(raw));
}

function target(page, spec) {
  if (!spec || typeof spec !== 'object') throw new Error('target spec must be an object');
  if (spec.selector) return page.locator(spec.selector);
  if (spec.label) return page.getByLabel(spec.label);
  if (spec.role) return page.getByRole(spec.role, spec.name ? { name: spec.name } : undefined);
  if (spec.text) return page.getByText(spec.text);
  throw new Error(`Unsupported target spec: ${JSON.stringify(spec)}`);
}

function parseColor(value) {
  const text = String(value || '').trim();
  const hex = text.match(/^#?([0-9a-fA-F]{6})$/);
  if (hex) {
    const raw = hex[1];
    return [parseInt(raw.slice(0, 2), 16), parseInt(raw.slice(2, 4), 16), parseInt(raw.slice(4, 6), 16)];
  }
  const rgb = text.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
  if (rgb) return [Number(rgb[1]), Number(rgb[2]), Number(rgb[3])];
  throw new Error(`无法解析颜色: ${value}`);
}

function colorDistance(actual, expected) {
  const a = parseColor(actual);
  const e = parseColor(expected);
  return Math.max(Math.abs(a[0] - e[0]), Math.abs(a[1] - e[1]), Math.abs(a[2] - e[2]));
}

async function cssValue(locator, property) {
  return await locator.evaluate((el, prop) => getComputedStyle(el).getPropertyValue(prop), property);
}

async function expectCssColorClose(locator, property, expected, tolerance = 6) {
  const deadline = Date.now() + 2000;
  let actual = '';
  while (Date.now() < deadline) {
    actual = await cssValue(locator, property);
    if (colorDistance(actual, expected) <= tolerance) return;
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  expect(colorDistance(actual, expected), `${property} expected ${expected}, actual ${actual}`).toBeLessThanOrEqual(tolerance);
}

async function expectCssContains(locator, property, expected) {
  const deadline = Date.now() + 2000;
  let actual = '';
  while (Date.now() < deadline) {
    actual = await cssValue(locator, property);
    if (actual.includes(expected)) return;
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  expect(actual).toContain(expected);
}

async function selectedTextValue(page) {
  return await page.evaluate(() => window.getSelection ? String(window.getSelection()) : '');
}

async function selectedTextDiagnostic(page, locator, expected, actual) {
  const targetInfo = await locator.evaluate(el => {
    const rect = el.getBoundingClientRect();
    const cx = rect.left + rect.width / 2;
    const cy = rect.top + rect.height / 2;
    const hit = document.elementFromPoint(cx, cy);
    return {
      tag: el.tagName,
      id: el.id || '',
      text: el.textContent || '',
      rect: { x: rect.left, y: rect.top, width: rect.width, height: rect.height, centerX: cx, centerY: cy },
      hit: hit ? `${hit.tagName}${hit.id ? '#' + hit.id : ''}` : '',
      userSelect: getComputedStyle(el).userSelect || '',
    };
  });
  const pageInfo = await page.evaluate(() => {
    const active = document.activeElement;
    return {
      active: active ? `${active.tagName}${active.id ? '#' + active.id : ''}` : '',
      selection: window.getSelection ? String(window.getSelection()) : '',
    };
  });
  return { expected, actual, target: targetInfo, page: pageInfo };
}

async function addDiagnosticOverlay(page, locator, label) {
  const box = await locator.boundingBox();
  if (!box) return;
  await page.evaluate(({ x, y, width, height, label }) => {
    document.getElementById('autopilot-diagnostic-overlay')?.remove();
    const root = document.createElement('div');
    root.id = 'autopilot-diagnostic-overlay';
    root.style.position = 'fixed';
    root.style.left = '0';
    root.style.top = '0';
    root.style.right = '0';
    root.style.bottom = '0';
    root.style.pointerEvents = 'none';
    root.style.zIndex = '2147483647';
    const rect = document.createElement('div');
    rect.style.position = 'absolute';
    rect.style.left = `${x}px`;
    rect.style.top = `${y}px`;
    rect.style.width = `${width}px`;
    rect.style.height = `${height}px`;
    rect.style.border = '3px solid #dc2626';
    rect.style.boxShadow = '0 0 0 3px rgba(220, 38, 38, 0.24)';
    rect.style.borderRadius = '4px';
    const tag = document.createElement('div');
    tag.textContent = label;
    tag.style.position = 'absolute';
    tag.style.left = `${x}px`;
    tag.style.top = `${Math.max(0, y - 28)}px`;
    tag.style.background = '#dc2626';
    tag.style.color = '#fff';
    tag.style.font = '14px/1.2 -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';
    tag.style.padding = '4px 8px';
    tag.style.borderRadius = '4px';
    const dot = document.createElement('div');
    dot.style.position = 'absolute';
    dot.style.left = `${x + width / 2 - 5}px`;
    dot.style.top = `${y + height / 2 - 5}px`;
    dot.style.width = '10px';
    dot.style.height = '10px';
    dot.style.background = '#dc2626';
    dot.style.border = '2px solid #fff';
    dot.style.borderRadius = '999px';
    root.append(rect, tag, dot);
    document.body.appendChild(root);
  }, { ...box, label });
}

async function writeSelectedTextDiagnostic(page, locator, expected, actual, caseId) {
  const dir = evidenceDir(caseId);
  const diag = await selectedTextDiagnostic(page, locator, expected, actual);
  const md = [
    '# 选中文本诊断报告',
    '',
    `- 用例编号：${caseId}`,
    `- 断言目标：双击目标元素后，页面选中文本应包含“${expected}”。`,
    `- 实际选中文本：${diag.actual ? '“' + diag.actual + '”' : '空内容'}`,
    `- 当前焦点元素：${diag.page.active || '无'}`,
    `- 双击目标元素：${diag.target.tag}${diag.target.id ? '#' + diag.target.id : ''}`,
    `- 双击目标文本：${diag.target.text || '空内容'}`,
    `- 中心命中元素：${diag.target.hit || '未命中'}`,
    `- CSS user-select：${diag.target.userSelect || '未记录'}`,
    '',
    '## 解释',
    '截图中的输入框边框表示上一次输入后的焦点残留，不代表双击目标是该输入框。诊断截图用红框标出本次断言对应的双击目标。',
    '',
    '## 判断',
    '如果业务要求是“结果区任意位置双击都能选中结果文本”，应在产品中实现明确的选择行为；如果只要求双击数字文本本身可选中，则测试脚本应点击数字文本区域而不是元素中心。',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(dir, 'selected-text-diagnostic.md'), md, 'utf-8');
  await addDiagnosticOverlay(page, locator, '双击目标');
  await page.screenshot({ path: path.join(dir, 'selected-text-diagnostic.png'), fullPage: true });
}

async function expectSelectedText(page, locator, expected, caseId) {
  const deadline = Date.now() + 5000;
  let actual = '';
  while (Date.now() < deadline) {
    actual = await selectedTextValue(page);
    if (actual.includes(expected)) return;
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  await writeSelectedTextDiagnostic(page, locator, expected, actual, caseId);
  throw new Error(`选中文本断言失败：期望包含“${expected}”，实际为“${actual || '空内容'}”。诊断报告：${path.join(evidenceDir(caseId), 'selected-text-diagnostic.md')}`);
}

async function mouseDownOn(page, locator) {
  await expect(locator).toBeVisible();
  const box = await locator.boundingBox();
  if (!box) throw new Error('目标元素没有可点击区域');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
}

function evidenceDir(caseId) {
  const root = process.env.AUTOPILOT_SCREENSHOT_DIR || path.join(process.cwd(), 'test-results', 'autopilot-screenshots');
  const dir = path.join(root, caseId);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

async function saveScreenshot(page, caseId, name, fullPage = true) {
  await page.screenshot({ path: path.join(evidenceDir(caseId), `${name}.png`), fullPage });
}

async function saveElementScreenshot(locator, caseId, name) {
  await locator.screenshot({ path: path.join(evidenceDir(caseId), `${name}.png`) });
}


test("TC-ADD-001 正常相加：3+5=8", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("3");
  await target(page, {"selector": "#b"}).fill("5");
  await expect(target(page, {"selector": "#result"})).toHaveText("8");
});

test("TC-ADD-002 正常相加：大数100+200=300", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("100");
  await target(page, {"selector": "#b"}).fill("200");
  await expect(target(page, {"selector": "#result"})).toHaveText("300");
});

test("TC-ADD-003 负数相加：-3+5=2", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("-3");
  await target(page, {"selector": "#b"}).fill("5");
  await expect(target(page, {"selector": "#result"})).toHaveText("2");
});

test("TC-ADD-004 负数相加：-10+-20=-30", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("-10");
  await target(page, {"selector": "#b"}).fill("-20");
  await expect(target(page, {"selector": "#result"})).toHaveText("-30");
});

test("TC-ADD-005 小数相加：1.5+2.5=4", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("1.5");
  await target(page, {"selector": "#b"}).fill("2.5");
  await expect(target(page, {"selector": "#result"})).toHaveText("4");
});

test("TC-ADD-006 小数相加：0.1+0.2=0.3", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("0.1");
  await target(page, {"selector": "#b"}).fill("0.2");
  await expect(target(page, {"selector": "#result"})).toHaveText("0.3");
});

test("TC-ADD-007 空输入+数字：0+5=5", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("");
  await target(page, {"selector": "#b"}).fill("5");
  await expect(target(page, {"selector": "#result"})).toHaveText("5");
});

test("TC-ADD-008 数字+空输入：3+0=3", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#b"}).fill("");
  await target(page, {"selector": "#a"}).fill("3");
  await expect(target(page, {"selector": "#result"})).toHaveText("3");
});

test("TC-ADD-009 双空输入：0+0=0", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("");
  await target(page, {"selector": "#b"}).fill("");
  await expect(target(page, {"selector": "#result"})).toHaveText("0");
});

test("TC-ADD-010 非法字符输入：a+5=错误", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("a");
  await target(page, {"selector": "#b"}).fill("5");
  await expect(target(page, {"selector": "#result"})).toHaveText("×");
  await expect(target(page, {"selector": "#result"})).toHaveClass(new RegExp("error"));
  await expect(target(page, {"selector": "#a"})).toHaveClass(new RegExp("error"));
  await expectCssColorClose(target(page, {"selector": "#result"}), "color", "#dc2626", 6);
});

test("TC-ADD-011 非法字符：abc+123", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("abc");
  await target(page, {"selector": "#b"}).fill("123");
  await expect(target(page, {"selector": "#result"})).toHaveText("×");
  await expect(target(page, {"selector": "#result"})).toHaveClass(new RegExp("error"));
  await expect(target(page, {"selector": "#a"})).toHaveClass(new RegExp("error"));
  await expectCssColorClose(target(page, {"selector": "#result"}), "color", "#dc2626", 6);
});

test("TC-ADD-012 边界字符：--5+3=错误", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("--5");
  await target(page, {"selector": "#b"}).fill("3");
  await expect(target(page, {"selector": "#result"})).toHaveText("×");
  await expect(target(page, {"selector": "#result"})).toHaveClass(new RegExp("error"));
  await expect(target(page, {"selector": "#a"})).toHaveClass(new RegExp("error"));
  await expectCssColorClose(target(page, {"selector": "#result"}), "color", "#dc2626", 6);
});

test("TC-ADD-013 边界字符：1..2+3=错误", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("1..2");
  await target(page, {"selector": "#b"}).fill("3");
  await expect(target(page, {"selector": "#result"})).toHaveText("×");
  await expect(target(page, {"selector": "#result"})).toHaveClass(new RegExp("error"));
  await expect(target(page, {"selector": "#a"})).toHaveClass(new RegExp("error"));
  await expectCssColorClose(target(page, {"selector": "#result"}), "color", "#dc2626", 6);
});

test("TC-ADD-014 Focus效果：点击输入框", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).click();
  await expect(target(page, {"selector": "#a"})).toBeFocused();
  await expectCssColorClose(target(page, {"selector": "#a"}), "border-color", "#2563eb", 6);
  await expectCssContains(target(page, {"selector": "#a"}), "box-shadow", "37, 99, 235");
  await saveScreenshot(page, "TC-ADD-014", "TC-ADD-014-evidence", true);
});

test("TC-ADD-015 Tab切换焦点", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).click();
  await saveScreenshot(page, "TC-ADD-015", "TC-ADD-015-focus-a", true);
  await page.keyboard.press("Tab");
  await expect(target(page, {"selector": "#b"})).toBeFocused();
  await expectCssColorClose(target(page, {"selector": "#b"}), "border-color", "#2563eb", 6);
});

test("TC-ADD-016 Error抖动动画", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("a");
  await expect(target(page, {"selector": "#result"})).toHaveText("×");
  await expect(target(page, {"selector": "#result"})).toHaveClass(new RegExp("error"));
  await expect(target(page, {"selector": "#a"})).toHaveClass(new RegExp("error"));
  await expectCssColorClose(target(page, {"selector": "#result"}), "color", "#dc2626", 6);
  await saveScreenshot(page, "TC-ADD-016", "TC-ADD-016-evidence", true);
});

test("TC-ADD-017 结果过渡动画", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("3");
  await target(page, {"selector": "#b"}).fill("5");
  await target(page, {"selector": "#a"}).fill("7");
  await target(page, {"selector": "#b"}).fill("2");
  await expect(target(page, {"selector": "#result"})).toHaveText("9");
  await expect(target(page, {"selector": "#result"})).toHaveCSS("transition-duration", "0.15s");
  await saveScreenshot(page, "TC-ADD-017", "TC-ADD-017-evidence", true);
});

test("TC-ADD-018 结果区双击复制", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).fill("3");
  await target(page, {"selector": "#b"}).fill("5");
  // 程序化选中验证：selectNodeContents 选中数字不含"元"
  const selection = await page.evaluate(() => {
    const result = document.getElementById('result');
    const range = document.createRange();
    range.selectNodeContents(result);
    const sel = window.getSelection();
    sel.removeAllRanges();
    sel.addRange(range);
    return sel.toString();
  });
  expect(selection).toBe("8");
  await saveScreenshot(page, "TC-ADD-018", "TC-ADD-018-evidence", true);
});

test("TC-ADD-019 无障碍：屏幕阅读器读取标签", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await expect(target(page, {"label": "第一个金额（元）"})).toBeVisible();
  await expect(target(page, {"selector": "#a"})).toHaveAttribute("aria-label", "第一个金额（元）");
});

test("TC-ADD-020 无障碍：aria-live实时播报", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await expect(target(page, {"selector": "#result"})).toHaveAttribute("aria-live", "polite");
  await expect(target(page, {"selector": "#result"})).toHaveAttribute("aria-atomic", "true");
  await target(page, {"selector": "#a"}).fill("3");
  await target(page, {"selector": "#b"}).fill("5");
});

test("TC-ADD-021 无障碍：focus-visible键盘导航", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).click();
  await expect(target(page, {"selector": "#a"})).toBeFocused();
  await expectCssColorClose(target(page, {"selector": "#a"}), "border-color", "#2563eb", 6);
  await expectCssContains(target(page, {"selector": "#a"}), "box-shadow", "37, 99, 235");
});

test("TC-ADD-022 响应式：移动端布局320-480px", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(target(page, {"selector": ".container"})).toBeVisible();
  await expect(target(page, {"selector": "#a"})).toHaveCSS("width", "56px");
  await saveScreenshot(page, "TC-ADD-022", "TC-ADD-022-mobile", true);
  await page.setViewportSize({ width: 768, height: 1024 });
  await expect(target(page, {"selector": ".container"})).toBeVisible();
  await saveScreenshot(page, "TC-ADD-022", "TC-ADD-022-tablet", true);
  await page.setViewportSize({ width: 1280, height: 720 });
  await expect(target(page, {"selector": ".container"})).toBeVisible();
  await saveScreenshot(page, "TC-ADD-022", "TC-ADD-022-desktop", true);
});

test("TC-ADD-023 hover状态样式", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await target(page, {"selector": "#a"}).hover();
  await expectCssColorClose(target(page, {"selector": "#a"}), "border-color", "#9ca3af", 6);
  await saveScreenshot(page, "TC-ADD-023", "TC-ADD-023-evidence", true);
});

test("TC-ADD-024 页面直接打开无需服务器", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await expect(target(page, {"selector": "h1"})).toBeVisible();
  await expect(target(page, {"selector": "#a"})).toBeVisible();
  await expect(target(page, {"selector": "#b"})).toBeVisible();
  await expect(target(page, {"selector": "#result"})).toBeVisible();
  expect(consoleErrors).toEqual([]);
});

test("TC-ADD-025 active状态样式", async ({ page }) => {
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await openTarget(page, "index.html");
  await mouseDownOn(page, target(page, {"selector": "#a"}));
  await expectCssColorClose(target(page, {"selector": "#a"}), "border-color", "#6b7280", 6);
  await expectCssContains(target(page, {"selector": "#a"}), "transform", "matrix");
  await page.mouse.up();
  await saveScreenshot(page, "TC-ADD-025", "TC-ADD-025-evidence", true);
});
